# Generated by Django 5.2.8 on 2025-11-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Brand', models.CharField(max_length=20)),
                ('Price', models.FloatField()),
                ('manufacture_data', models.DateField()),
                ('Expiry_date', models.DateField()),
                ('warranty', models.CharField(max_length=10)),
            ],
        ),
    ]
